### ISSUE TITLE
Is all the patterns code should work by copy-paste?

### ISSUE THREAD

**Issue by trycontrolmymind** [RefactoringGuru/design-patterns-typescript#1]
I think, all the patterns from this repository should work by "copy and paste", or am i wrong?

For example, in this part of code, typescript will say, that `state` property does not exists on Subject.

https://github.com/RefactoringGuru/design-patterns-typescript/blob/11ed2f6c52b7ce037248f73e5b3f959cc1865450/src/Observer/Conceptual/index.ts#L145

**Comment by neochief** [comment]
Hi!

Depending on your actual real-life implementation, you might benefit from declaring methods of dealing with the "state" in the Subject interface, so that all observers could deal with all kinds of Subjects reliably. The problem with showing this in an example is that any real app might have this "state" represented very differently. This might be a simple field or a whole bunch of different fields.
